services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      # Add any environment variables needed for your stock analysis app
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    volumes:
      - .:/app
    networks:
      - chatbot_network

volumes:
  # Remove unused volumes if they are not relevant
  chatbot_data:
    driver: local

networks:
  chatbot_network:
    driver: bridge
