services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      # Link the environment variables to the .env file
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
    networks:
      - chatbot_network

volumes:
  chatbot_data:
    driver: local

networks:
  chatbot_network:
    driver: bridge
